openapi: 3.0.2
info:
  title: Whitelisting Tool - OpenAPI definition
  description: |-
    The goal of this API is to manage the Ip lists that are registered for each operator, for them to be able to access 
    GN system through the network.
  contact:
    email: genesis_dev@expenti.com
  license:
    name: Expenti
    url: https://www.expenti.com/
  version: "0.3"
#servers:
#  - url: https://whitelisting-tool/api/v1
tags:
  - name: Operator
    description: Manage operators' whitelisted IPs
security:
  - BasicAuth: []
paths:
  /operator:
    get:
      tags:
        - Operator
      summary: Gets all operators
      description: Gets all operators
      operationId: getOperators
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Operator'
        '500':
          description: Internal server error
    post:
      tags:
        - Operator
      summary: Add a new operator
      description: Creates the operator in the storage with an empty list of IPs
      operationId: addOperator
      requestBody:
        description: New Operator
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Operator'
        required: true
      responses:
        '201':
          description: Successful operation
        '400':
          description: Invalid input format or the partner already existed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        '500':
          description: Internal server error
  /operator/{operatorCode}/ip:
    get:
      tags:
        - Operator
      summary: Get an Operator's IP list
      description: Get an Operator's whitelisted IP list
      operationId: getOperatorIpList
      parameters:
        - name: operatorCode
          in: path
          description: Operator code
          required: true
          schema:
            type: string
            maxLength: 50
            example: Operator_1
        - name: whitelistType
          in: query
          description: Type of whitelist to retrieve
          required: true
          schema:
            type: string
            enum:
              - API
              - BACK_OFFICE
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
              example: ["1.2.3.4","1.2.3.5/31"]
        '400':
          description: Invalid input format
        '404':
          description: Operator not found
        '500':
          description: Internal server error
    patch:
      tags:
        - Operator
      summary: Update partner's IP list
      description: Add or remove IPs from partner's list
      operationId: updateIps
      parameters:
        - name: operatorCode
          in: path
          description: Operator code
          required: true
          schema:
            type: string
            maxLength: 50
            example: Operator_1
      requestBody:
        description: IP or CIDR block array
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateIpsRequest'
        required: true
      responses:
        '201':
          description: Successful operation
        '400':
          description: Invalid input format
        '404':
          description: Operator not found
        '500':
          description: Internal server error
components:
  schemas:
    Operator:
      type: object
      required:
        - code
      properties:
        code:
          type: string
          description: Operator code
          minLength: 1
          maxLength: 50
      example:
        code: Operator_1
    ApiErrorResponse:
      type: object
      required:
        - errorCode
        - errorMessage
      properties:
        errorCode:
          type: string
        errorMessage:
          type: string
      example:
        errorCode: EXISTING_OPERATOR
        errorMessage: The new operator already exists in Git
    UpdateIpsRequest:
      type: object
      required:
        - whitelistType
        - ips
      properties:
        whitelistType:
          type: string
          enum:
            - API
            - BACK_OFFICE
          description: Type of whitelist to update
        updateType:
          type: string
          enum:
            - ADDITION
            - REMOVAL
        ips:
          type: array
          items:
            type: string
            minLength: 1
            maxLength: 50
            pattern: ^(?:(?:25[0-5]|2[0-4][0-9]|1?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|1?[0-9][0-9]?)(?:\/(?:3[0-2]|[12]?[0-9]))?$
          description: List of IPs/CIDR blocks to add or remove
      example:
        whitelistType: API
        updateType: REMOVAL
        ips: [ "1.2.3.4", "1.2.3.5/31" ]
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
